### ISSUE TITLE
list styles switch to numeric for one item

### ISSUE THREAD

**Issue by deiferni** [4teamwork/docxcompose#11]
create a composed file based on

master: [header_broken_listing.docx](https://github.com/4teamwork/docxcompose/files/2184094/header_broken_listing.docx)
appended doc: [broken_listing.docx](https://github.com/4teamwork/docxcompose/files/2184096/broken_listing.docx)

the list style for the first item is switched for the first item only.
file: [switched_list_styles.docx](https://github.com/4teamwork/docxcompose/files/2184100/switched_list_styles.docx)

**Comment by buchi** [comment]
Not really fixed in #17 

expected listing:
```
a)	aaaaaaa.
b)	behhh.
c)	cehhhh.
```

before fix #17:
```
1.	aaaaaaa.
a)	behhh.
b)	cehhhh.
```

after fix #17:
```
1.	aaaaaaa.
2.	behhh.
3.	cehhhh.
```
