### ISSUE TITLE
SmartArt results in corrupt document.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/docxcompose#23]
Create a composed file based on

master:  [header.docx](https://github.com/4teamwork/docxcompose/files/2548768/header.docx)
appended doc:  [smartart.docx](https://github.com/4teamwork/docxcompose/files/2548770/smartart.docx)

this will result in a document which is considered corrupt by word. the document can be recovered by word, but the smart-art item is missing from the result: [corrupt.docx](https://github.com/4teamwork/docxcompose/files/2548772/corrupt.docx)

**Comment by a-w** [comment]
Almost the same if appended document contains any pixmaps.  Then Word says (under details):

> Unknown error
> Location: Part: /word/header1.xml, Line 2, Column:0

However, if I open header1.xml with an XML editor, it looks (at least formally) OK.
The document can be recovered. Unlike the smartart example above, all pixmaps are present.
