### ISSUE TITLE
This is only a q, is the merge docx really work?

### ISSUE THREAD

**Issue by tsabbay** [4teamwork/docxcompose#41]
Hi,
We would like to know if the docx will also merge styles ?
Any known issues?

**Comment by buchi** [comment]
It works for our use case and yes it does merge styles.
Known issues are tracked [here](https://github.com/4teamwork/docxcompose/issues) 😉

**Comment by tsabbay** [comment]
Strange, we tested it quite a lot, and i wonder if there is a form/changes to be done as the default merge, is not working, lot of styling, images are being removed from the merge doc.
