### ISSUE TITLE
Word found unreadable content (Table properties)

### ISSUE THREAD

**Issue by W1M0R** [4teamwork/docxcompose#61]
Hi, thanks for developing this very useful library.

I use docxcompose to concatenate two docx files. Word has no problem opening the two files individually, but  after concatenating it, Word produces the following error:

```
Word found unreadable content in 'The Document Name'. Do you want to recover the contents of this document?
```

Word manages to recover the file, and everything seems fine. A dialog appears titled `Show Repairs`, and all errors in the list are named `Table Properties`. 

One of my documents contains a set of tables that have table captions.

**Comment by sheerinZ** [comment]
similar error for me too.. someone plz answer..

**Comment by peteyb** [comment]
We are experiencing this issue when using the attached docx file

[Data_analysis_task_LGky1Ke.docx](https://github.com/4teamwork/docxcompose/files/10245125/Data_analysis_task_LGky1Ke.docx)
