### ISSUE TITLE
Header/Footer issue when merging with a multi-sections document

### ISSUE THREAD

**Issue by macpoupou** [4teamwork/docxcompose#79]
My master document has two sections with differents headers.
If I merge another document with a single section... I have no issue. Added content takes the last previous section header.
But if I try to merge a document with multiple sections, all headers/footers of each sections are automaticaly replaced by the first header or footer.

**Comment by macpoupou** [comment]
I found a workaround... Before to merge a document, I generate a document by section... In this case, I have no issue.

In addition, before to merge each "section document", I have to append a new section and change its orientation, page_width, page_height and some other properties (pgNumType)...

**Comment by mxblsdl** [comment]
@macpoupou Can you provider a code sample with your proposed workaround? 
I'm facing the same issue of trying to merge multiple documents with different headers and footers.

**Comment by njohner** [comment]
Oh I think it's your lucky day, we ran into this issue, so I hope I fixed it here: https://github.com/4teamwork/docxcompose/pull/82
Fix does not cover all issues with section properties though, see description and comments in code.
